services:
  nginx:
    image: nginx:1.27.0-alpine
    container_name: ${NGINX_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - ${NGINX_PORT_OUT}:${NGINX_PORT}
      - ${NGINX_SSL_OUT}:${NGINX_SSL}
    volumes:
      - ./etc/nginx/conf.d:/etc/nginx/conf.d:ro
      # Default directory.
      #- :/usr/share/nginx/html
    #env_file:
    #  - ./.env

  vue-app:
    image: ${VUE_IMAGE_NAME}
    container_name: ${VUE_CONTAINER_NAME}
    build:
      dockerfile: Dockerfile.dev
      args:
        VUE_APP_NAME: ${PROJECT_NAME}
        VUE_PPORT: ${VUE_PORT}
    #command: sh -c ""
    restart: unless-stopped
    #ports:
    #  - ${VUE_PORT_OUT}:${VUE_PORT}
    volumes:
      - ./src:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    #env_file:
    #  - ./.env
    depends_on:
      - nginx
  
volumes:
  node_modules: