services:
  nginx:
    image: nginx:1.27.0-alpine
    restart: unless-stopped
    ports:
      - ${NGINX_PORT_OUT}:${NGINX_PORT}
      - ${NGINX_SSL_OUT}:${NGINX_SSL}
    volumes:
      - ./etc/nginx/conf.d:/etc/nginx/conf.d:ro
      # Default directory.
      #- :/usr/share/nginx/html

  vue-app:
    #image: ${PROJECT_NAME}-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    #container_name: ${PROJECT_NAME}-dev_c
    restart: unless-stopped
    #ports:
    #  - ${VUE_PORT_OUT}:${VUE_PORT}
    volumes:
      - node_modules:/app/node_modules
      - ./src:/app
    environment:
      - NODE_ENV=development
      - VUE_APP_NAME=${PROJECT_NAME}
      - VUE_PORT=${VUE_PORT}
    #env_file:
    #  - ./.env
    depends_on:
      - nginx
  
volumes:
  node_modules: